# Generated by Django 3.2.9 on 2021-11-10 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='SubJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, verbose_name='Название')),
                ('CostForOne', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Цена ед. без НДС')),
                ('Quantity', models.BigIntegerField(verbose_name='Кол-во')),
            ],
        ),
        migrations.CreateModel(
            name='PassportOfObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, verbose_name='Название')),
                ('Jobs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.jobs')),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='CategoryOfWork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.subjobs'),
        ),
    ]
