# Generated by Django 3.2.9 on 2021-11-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='CategoryOfWork',
        ),
        migrations.AddField(
            model_name='jobs',
            name='CategoryOfWork',
            field=models.ManyToManyField(blank=True, null=True, to='main.SubJobs'),
        ),
        migrations.RemoveField(
            model_name='passportofobject',
            name='Jobs',
        ),
        migrations.AddField(
            model_name='passportofobject',
            name='Jobs',
            field=models.ManyToManyField(blank=True, null=True, to='main.Jobs'),
        ),
    ]
