# Generated by Django 3.2.9 on 2021-11-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211110_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Объем')),
                ('Accreditation', models.ManyToManyField(to='main.SubJobs')),
            ],
        ),
    ]
