# Generated by Django 3.2.9 on 2021-11-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_counterparty'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='Name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='Accreditation',
            field=models.ManyToManyField(blank=True, null=True, to='main.SubJobs'),
        ),
    ]
